### ISSUE TITLE
Placeholder for Players Online ? 

### ISSUE THREAD

**Issue by vxkShelby** [T3CC4/SimpleTabList#2]
Is there option to view how many player are online in tablist ? i mean "4/50"

**Comment by F02K** [comment]
You can use placeholders from placeholderapi

**Comment by o0sh4d0w0o** [comment]
> Is there option to view how many player are online in tablist ? i mean "4/50"

You can do it like that : 
```yml
Footer:
  Use: true
  Content:
  - 'Online players : %server_online%/%server_max_players%'
  ```
  
  You'll get somthing like that : 
  
![image](https://github.com/TheYIMIR/SimpleTabList/assets/25451887/8f0be1cb-39d3-4877-8c9b-0ed597f21ee8)

Don't forget to execute command `/papi ecloud download Server` to access to these placeholders.
